/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.carrentals;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ONAWOLA
 */
public class NewCustomer extends javax.swing.JFrame {

    private final String INSERT_USER_SQL = "INSERT INTO customer"
            + "  (customerid, l_name, f_name, city) VALUES "
            + " (?,?,?,?);";

    // For use in creating dialogs and making them modal
    private JFrame dialogParent;
    private Connection con;
    private PreparedStatement PreparedStatementDb = null;

    /**
     * Creates new form NewJFrame
     */
    public NewCustomer() {
        initComponents();
    }

    public NewCustomer(JFrame parent, Connection connection) {
        initComponents();
        this.dialogParent = parent;
        this.con = connection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginHeader = new javax.swing.JLabel();
        jTxtCusId = new javax.swing.JTextField();
        lablelLoginUserName = new javax.swing.JLabel();
        jTxtLName = new javax.swing.JTextField();
        lablelLoginUserName1 = new javax.swing.JLabel();
        jTxtFName = new javax.swing.JTextField();
        lablelLoginUserName2 = new javax.swing.JLabel();
        jTxtCity = new javax.swing.JTextField();
        lablelLoginUserName3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jBtnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        loginHeader.setText("Add Customer");
        getContentPane().add(loginHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
        getContentPane().add(jTxtCusId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 140, -1));

        lablelLoginUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lablelLoginUserName.setText("Customer ID");
        getContentPane().add(lablelLoginUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));
        getContentPane().add(jTxtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 140, -1));

        lablelLoginUserName1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lablelLoginUserName1.setText("Last Name");
        getContentPane().add(lablelLoginUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));
        getContentPane().add(jTxtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 140, -1));

        lablelLoginUserName2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lablelLoginUserName2.setText("First Name");
        getContentPane().add(lablelLoginUserName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));
        getContentPane().add(jTxtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 140, -1));

        lablelLoginUserName3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lablelLoginUserName3.setText("City");
        getContentPane().add(lablelLoginUserName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jBtnAdd.setText("Add");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        dialogParent.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        String lastName = jTxtLName.getText().trim();
        String city = jTxtCity.getText().trim();
        String firstName = jTxtFName.getText().trim();
        try {
            Integer cusId = Integer.parseInt(jTxtCusId.getText().trim());
            try {
                PreparedStatementDb = con.prepareStatement(INSERT_USER_SQL);
                PreparedStatementDb.setInt(1, cusId);
                PreparedStatementDb.setString(2, lastName);
                PreparedStatementDb.setString(3, firstName);
                PreparedStatementDb.setString(4, city);
                PreparedStatementDb.executeUpdate();
                JOptionPane.showMessageDialog(jBtnAdd, "Data Saved Successfully");
                jTxtLName.setText("");
                jTxtCity.setText("");
                jTxtFName.setText("");
                jTxtCusId.setText("");
            } catch (SQLException e) {
                e.printStackTrace();
            } finally {
                // finally block used to close resources
                try {
                    PreparedStatementDb.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }// end try
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(jBtnAdd, "Enter a Customer ID");
        }
    }//GEN-LAST:event_jBtnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTxtCity;
    private javax.swing.JTextField jTxtCusId;
    private javax.swing.JTextField jTxtFName;
    private javax.swing.JTextField jTxtLName;
    private javax.swing.JLabel lablelLoginUserName;
    private javax.swing.JLabel lablelLoginUserName1;
    private javax.swing.JLabel lablelLoginUserName2;
    private javax.swing.JLabel lablelLoginUserName3;
    private javax.swing.JLabel loginHeader;
    // End of variables declaration//GEN-END:variables
}
